version: "3"

services:
    redis:
        container_name: redis_cache
        image: redis:alpine
        expose:
            - 6379
        networks:
            - app-network

    theft-processor:
        build:
            context: .
            dockerfile: Dockerfile
        image: theft_processor_image
        container_name: theft_processor_container
        restart: unless-stopped
        env_file: .env
        ports:
            - "4000:4000"
        links:
            - pgdb_container
            - mongodb_container
            - redis:redis_cache
        depends_on:
            - pgdb_container
            - mongodb_container
            - redis
        volumes:
            - .:/home/node/app
            - node_modules:/home/node/app/node_modules
        environment:
            - REDIS_URL=redis://redis-cache
            - PG_PORT=54320
            - PG_PASSWORD=postgres
            - PG_USER=postgres
            - PG_HOST=host.docker.internal
        networks:
            - app-network
        command: npm start

    pgdb_container:
        image: postgres
        environment:
            POSTGRES_DB: theft_processor
            POSTGRES_PASSWORD: postgres
        ports:
            - "54320:5432"
        restart: always
        networks:
            - app-network
        volumes:
            - ./pgdb_container:/var/lib/postgresql/data

    mongodb_container:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: rootpassword
        ports:
            - 27017:27017
        volumes:
            - mongodb_data_container:/data/db

networks:
    app-network:
        driver: bridge

volumes:
    node_modules:
    mongodb_data_container:
