version: "3"

services:
    theft_processor_redis_cache:
        expose:
            - 6379

    theft_processor_zookeeper_container:
        ports:
            - "2181:2181"

    theft_processor_kafka_container:
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: host.docker.internal
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_ZOOKEEPER_CONNECT: theft_processor_zookeeper_container:2181
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
            KAFKA_DELETE_TOPIC_ENABLE: 'true'
            KAFKA_CREATE_TOPICS: "topic-test:1:1"

    theft_processor_container:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        env_file: .env
        ports:
            - "7000:7000"
        environment:
            - REDIS_URL=redis://redis-cache
            - PG_PORT=54321
            - PG_PASSWORD=postgres
            - PG_NAME=postgres
            - PG_HOST=host.docker.internal
            - KAFKA_ADVERTISED_HOST_NAME=host.docker.internal
            - KAFKA_ADVERTISED_PORT=9092
        command: npm run start

    theft_processor_pg_container:
        environment:
            POSTGRES_DB: theft_processor
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
        ports:
            - "54321:5432"
